//! Deciding *who* a report is about, before anything is fetched.
//!
//! `FACT_CHECKING.md` §3.1: **"Nothing is fetched until the subject is pinned down, because
//! every downstream error inherits from getting this wrong."**
//!
//! That sentence is the whole justification for this module existing before the fetching it
//! guards. A report about the wrong company is not a report with a mistake in it — it is
//! wrong in every section, **internally consistent, and fully cited**. Every quote is
//! verbatim, every source resolves, every claim traces. It passes all four of the golden
//! set's measures. There is no check anywhere downstream that catches it, which is why the
//! check has to be here.
//!
//! # What this module is, and what it is not
//!
//! It is the **gate**: given candidates that something else produced, decide whether we know
//! who we are talking about. It does not generate candidates — that is discovery, and it
//! needs the fetching that this gate exists to authorise.
//!
//! Building the gate first is deliberate. Written afterwards it would be a check bolted onto
//! a pipeline that already runs without it, and every code path that predates the check is a
//! path that can skip it.
//!
//! # Why an enum here, when a tagged union measured *worse* in ADR 0004
//!
//! [ADR 0004](../../../docs/decisions/0004-require-every-property.md) found that making an
//! invalid state unrepresentable made a model *less* likely to give the right answer: a
//! one-token escape hatch outcompetes a nested object when a sampler is choosing between
//! them.
//!
//! **That finding is about samplers, not about types.** Nothing here is generated by a
//! model — [`resolve`] is ordinary Rust choosing a branch, so the enum costs nothing and
//! buys the thing enums are for: a caller cannot read the resolved entity without first
//! handling the case where there isn't one.

use serde::{Deserialize, Serialize};

/// One thing the subject might refer to.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Candidate {
    /// What it calls itself.
    pub name: String,
    /// The domain its own pages, profiles and documentation agree on (§3.1 step 3).
    pub canonical_domain: String,
    /// One line telling it apart from the others. This is what a reader picks between, so
    /// it has to distinguish rather than describe: "the note-taking app" beats "a software
    /// company" when three candidates are all software companies.
    pub what_it_is: String,
    /// How well this matches the subject, in `0.0..=1.0`.
    pub confidence: f32,
}

impl Candidate {
    /// Clamped, because a score outside the range is a bug in whatever produced it and
    /// comparing against a floor would then silently do the wrong thing.
    #[must_use]
    pub fn score(&self) -> f32 {
        self.confidence.clamp(0.0, 1.0)
    }
}

/// What we concluded about who the subject is.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "kind")]
pub enum Resolution {
    /// One clear answer. Fetching may proceed.
    Resolved { entity: Candidate },

    /// Several plausible answers, too close to choose between.
    ///
    /// **The report does not get written.** One chip click prevents an entire wrong report
    /// — PRODUCT_SPEC §3 — and the arithmetic is not close: a question costs a reader about
    /// three seconds, and a confidently wrong report costs them their trust in every other
    /// number we ever show them.
    Ambiguous {
        question: String,
        candidates: Vec<Candidate>,
    },

    /// Nothing matched well enough to be worth showing.
    ///
    /// Distinct from [`Self::Ambiguous`] on purpose. "I found several and cannot choose"
    /// is answerable by a reader in one click; "I found nothing convincing" is not, and
    /// offering a list of things we do not believe in would invite them to pick one.
    NothingFound { checked: Vec<String> },
}

/// How close two candidates have to be before we stop guessing.
///
/// Below this, the gap between first and second is smaller than the noise in whatever
/// produced the scores, so picking the top one is a coin flip presented to the reader as a
/// fact. Above it, the scoring is making a real distinction and asking would be the
/// interrogation `PRODUCT_SPEC.md` §3 warns against — *"never ask something inferable from
/// the input"*.
///
/// 0.15 is a starting value, not a measured one, and it is the number most likely to be
/// wrong in this module. It belongs in the golden set once discovery produces real scores.
pub const AMBIGUITY_MARGIN: f32 = 0.15;

/// The weakest candidate worth showing anyone.
///
/// Below this we found things, and we do not believe any of them. Presenting a list we do
/// not believe in is worse than reporting nothing: a reader picks one, and now the wrong
/// answer carries their endorsement as well as ours.
pub const MINIMUM_CONFIDENCE: f32 = 0.35;

/// Decide who the subject is.
///
/// Pure: no clock, no network, no model. Every branch below is reachable from a unit test,
/// which matters because this is the code that decides whether a wrong report gets written.
#[must_use]
pub fn resolve(subject: &str, mut candidates: Vec<Candidate>, checked: Vec<String>) -> Resolution {
    candidates.retain(|c| c.score() >= MINIMUM_CONFIDENCE);

    // Descending by score. `total_cmp` rather than `partial_cmp().unwrap()`: a NaN
    // confidence would panic the sort, and a panic here takes down a request over a
    // malformed score somebody else produced.
    candidates.sort_by(|a, b| b.score().total_cmp(&a.score()));

    let Some(best) = candidates.first().cloned() else {
        return Resolution::NothingFound { checked };
    };

    let tied: Vec<Candidate> = candidates
        .iter()
        .filter(|c| best.score() - c.score() < AMBIGUITY_MARGIN)
        .cloned()
        .collect();

    if tied.len() > 1 {
        return Resolution::Ambiguous {
            question: question_for(subject),
            candidates: tied,
        };
    }

    Resolution::Resolved { entity: best }
}

/// The question a reader is asked when we cannot choose.
///
/// Built here rather than in the frontend so the wording has one home and can be tested.
/// It quotes the reader's own words back: `PRODUCT_SPEC.md` §3 shows *"Which Notion do you
/// mean?"*, and the point of the quotation is that the reader recognises the ambiguity as
/// belonging to what they typed rather than to our confusion.
#[must_use]
pub fn question_for(subject: &str) -> String {
    let trimmed = subject.trim();
    if trimmed.is_empty() {
        // Unreachable through the API, which rejects short prompts long before this. Still
        // handled, because a question reading `Which  do you mean?` would be worse than a
        // generic one and this is not the place to find that out.
        return "Which one do you mean?".to_owned();
    }
    // Long free-form descriptions do not quote well — "Which an app that helps small farms
    // sell to local restaurants do you mean?" is nonsense. A brand name does.
    if trimmed.split_whitespace().count() > 4 {
        return "Which of these did you mean?".to_owned();
    }
    format!("Which {trimmed} do you mean?")
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    fn candidate(name: &str, domain: &str, confidence: f32) -> Candidate {
        Candidate {
            name: name.to_owned(),
            canonical_domain: domain.to_owned(),
            what_it_is: format!("{name}, a thing"),
            confidence,
        }
    }

    #[test]
    fn one_clear_candidate_resolves() {
        let r = resolve(
            "Notion",
            vec![candidate("Notion", "notion.so", 0.94)],
            vec![],
        );
        match r {
            Resolution::Resolved { entity } => assert_eq!(entity.canonical_domain, "notion.so"),
            other => panic!("expected Resolved, got {other:?}"),
        }
    }

    #[test]
    fn a_clear_winner_resolves_even_with_others_present() {
        // The runner-up is real and much weaker. Asking here would be the interrogation
        // PRODUCT_SPEC §3 warns against.
        let r = resolve(
            "Notion",
            vec![
                candidate("Notion", "notion.so", 0.95),
                candidate("Notion Press", "notionpress.com", 0.51),
            ],
            vec![],
        );
        assert!(matches!(r, Resolution::Resolved { .. }), "{r:?}");
    }

    #[test]
    fn two_close_candidates_are_ambiguous() {
        // The case the module exists for. Picking the 0.71 here would produce a report that
        // is wrong throughout, internally consistent and fully cited.
        let r = resolve(
            "Notion",
            vec![
                candidate("Notion", "notion.so", 0.71),
                candidate("Notion Press", "notionpress.com", 0.66),
            ],
            vec![],
        );
        match r {
            Resolution::Ambiguous {
                question,
                candidates,
            } => {
                assert_eq!(candidates.len(), 2);
                assert_eq!(question, "Which Notion do you mean?");
            }
            other => panic!("expected Ambiguous, got {other:?}"),
        }
    }

    #[test]
    fn only_the_tied_candidates_are_offered() {
        // A third, clearly weaker candidate must not appear as a chip. Every extra option
        // makes the question slower to answer without making it more answerable.
        let r = resolve(
            "Acme",
            vec![
                candidate("Acme Software", "acme.dev", 0.80),
                candidate("Acme Tools", "acmetools.com", 0.74),
                candidate("Acme Bakery", "acmebakery.co", 0.40),
            ],
            vec![],
        );
        match r {
            Resolution::Ambiguous { candidates, .. } => {
                assert_eq!(candidates.len(), 2);
                assert!(candidates.iter().all(|c| c.name.starts_with("Acme ")));
                assert!(!candidates.iter().any(|c| c.name.contains("Bakery")));
            }
            other => panic!("expected Ambiguous, got {other:?}"),
        }
    }

    #[test]
    fn candidates_below_the_floor_are_never_offered() {
        // We found things and believe none of them. A list we do not believe in invites a
        // reader to pick one, and now the wrong answer carries their endorsement too.
        let r = resolve(
            "Zxqv",
            vec![
                candidate("Zxqv Ltd", "zxqv.example", 0.20),
                candidate("Zxqvy", "zxqvy.example", 0.18),
            ],
            vec!["a web search".to_owned()],
        );
        match r {
            Resolution::NothingFound { checked } => assert_eq!(checked, ["a web search"]),
            other => panic!("expected NothingFound, got {other:?}"),
        }
    }

    #[test]
    fn no_candidates_reports_what_was_checked() {
        // An auditable negative, the same treatment a missing report section gets:
        // FACT_CHECKING.md §5.4. "Nothing found" with no list is unfalsifiable.
        let r = resolve("Zxqv", vec![], vec!["a web search".to_owned()]);
        match r {
            Resolution::NothingFound { checked } => assert_eq!(checked.len(), 1),
            other => panic!("expected NothingFound, got {other:?}"),
        }
    }

    #[test]
    fn a_nan_confidence_does_not_panic() {
        // Whatever produces these scores will one day divide by zero. A panic here takes
        // down a request the reader is waiting on, so NaN sorts as the lowest score and
        // falls below the floor rather than taking the process with it.
        let r = resolve(
            "Acme",
            vec![
                candidate("Acme Software", "acme.dev", f32::NAN),
                candidate("Acme Tools", "acmetools.com", 0.80),
            ],
            vec![],
        );
        match r {
            Resolution::Resolved { entity } => assert_eq!(entity.name, "Acme Tools"),
            other => panic!("expected Resolved, got {other:?}"),
        }
    }

    #[test]
    fn a_score_above_one_cannot_manufacture_a_winner() {
        // Clamping means an out-of-range score competes fairly instead of winning by
        // arithmetic. Both land at 1.0 here, which is a tie, which is a question.
        let r = resolve(
            "Acme",
            vec![
                candidate("Acme Software", "acme.dev", 9.9),
                candidate("Acme Tools", "acmetools.com", 1.0),
            ],
            vec![],
        );
        assert!(matches!(r, Resolution::Ambiguous { .. }), "{r:?}");
    }

    #[test]
    fn exactly_at_the_margin_is_a_clear_winner() {
        // The boundary, asserted so that changing the comparison direction fails a test
        // rather than quietly moving how often readers are interrupted.
        let r = resolve(
            "Acme",
            vec![
                candidate("A", "a.example", 0.80),
                candidate("B", "b.example", 0.80 - AMBIGUITY_MARGIN),
            ],
            vec![],
        );
        assert!(matches!(r, Resolution::Resolved { .. }), "{r:?}");
    }

    #[test]
    fn a_long_description_is_not_quoted_back_into_the_question() {
        // "Which an app that helps small farms sell to local restaurants do you mean?" is
        // not a sentence, and a reader who sees it stops trusting the rest of the page.
        let q = question_for("an app that helps small farms sell to local restaurants");
        assert_eq!(q, "Which of these did you mean?");
    }

    #[test]
    fn a_brand_name_is_quoted_back() {
        assert_eq!(question_for("  Notion  "), "Which Notion do you mean?");
        assert_eq!(question_for("Acme Tools"), "Which Acme Tools do you mean?");
    }

    #[test]
    fn a_resolution_round_trips_as_tagged_json() {
        // The frontend switches on `kind`. An untagged enum would serialise the three cases
        // to shapes that are only distinguishable by which fields happen to be present.
        let r = resolve(
            "Notion",
            vec![candidate("Notion", "notion.so", 0.9)],
            vec![],
        );
        let json = serde_json::to_value(&r).expect("serialise");
        assert_eq!(json["kind"], "resolved");
        let back: Resolution = serde_json::from_value(json).expect("deserialise");
        assert_eq!(back, r);
    }
}
